name: bedwars
main: cz.stefan.bedwars.main
version: alpha
author: pavelstef
commands:
  report:
    description: reports player
    usage: /report [<player>] 
  bedwars:
    aliases: [bw, bedw]